### ISSUE TITLE
SHMEM Transpose Kernel on 1 PE

### ISSUE THREAD

**Issue by jdinan** [ParRes/Kernels#10]
The SHMEM transpose kernel fails spectacularly when run on 1 PE.  The error is a result of ```free(Work_in_p)```, which is not allocated in single PE runs.

```
$ mpiexec.hydra -np 1 ./SHMEM/Transpose/transpose 10 1000
Parallel Research Kernels version 2.15
SHMEM matrix transpose: B = A^T
Number of ranks      = 1
Matrix order         = 1000
Number of iterations = 10
Tile size            = 32
Solution validates
Rate (MB/s): 6252.165050 Avg time (s): 0.002559
transpose(43428,0x7fff78246000) malloc: *** error for object 0x1: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

**Comment by rfvander** [comment]
Thanks, Jim. Yes, this is a known bug that has been fixed in the development repo, and that will be pushed to the public repo at the next release. Apologies for the inconvenience.

Rob

**Comment by jeffhammond** [comment]
@jdinan Is this resolved now?  We have merged the development repo, so I assume so.

**Comment by jdinan** [comment]
I have not run the code, but from inspection it appears to be fixed.  Although the fix seems to have left behind some whitespace splash damage.

**Comment by jeffhammond** [comment]
We have serious whitespace issues. At least we are mostly post-dos2unix...
