### ISSUE TITLE
use Travis caching

### ISSUE THREAD

**Issue by jeffhammond** [ParRes/Kernels#123]
I am a terrible human being for not implementing this sooner.  Many polar bears have died due to the hundreds of unnecessary MPICH builds I've run in AWS because of not caching them.

See https://docs.travis-ci.com/user/caching/#Fetching-and-storing-caches.

**Comment by zbeekman** [comment]
You're probably aware, but this only works with container based builds. Although you could probably save a ton of time by building stuff for Travis-CI OSX and deploy to bintray then re-download or do what I do and build custom Homebrew bottles and host them somewhere. I just use github issues as a CDN. Gets to be a bit of a maintenance headache depending how deep down the rabbit hole you go.

**Comment by jeffhammond** [comment]
I'm only doing containers now. If I was using sudo, I wouldn't need caching, because I could just download the rpms.

**Comment by jeffhammond** [comment]
`sudo` is now the recommended path.  Any big changes in Travis CI are just going to use that, which means caching doesn't matter.
