### ISSUE TITLE
Serial/DGEMM with MKL

### ISSUE THREAD

**Issue by steenax86** [ParRes/Kernels#256]
Hi,

The Make process in Serial/DGEMM is missing the `-mkl` flag for compiling DGEMM with MKL's `cblas_dgemm` and consequently produces the "`undefined reference to cblas_dgemm`" error. Adding` -mkl` to the compilation lines fixed this.

Thanks,
Steena

**Comment by jeffhammond** [comment]
I would solve this by adding a `BLAS_LIB` variable to `make.defs` and then add `BLAS_LIB=-mkl` to the `make.defs.intel` example but this is a rather trivial thing to solve, so I'm not sure that we need to do it.  The `dgemm` kernel is not particularly useful for most of the purposes for which we use the PRK project today.  If one wants to benchmark BLAS libraries, there are better ways.  The only purpose I see for the `dgemm` kernel is to measure compiler optimization, in which case one would not use the BLAS implementation except as a performance reference point.

**Comment by jeffhammond** [comment]
https://github.com/ParRes/Kernels/blob/master/common/make.defs.intel#L56 and https://github.com/ParRes/Kernels/blob/master/common/make.defs.llvm#L71 implement this feature, which is used in e.g. https://github.com/ParRes/Kernels/blob/master/Cxx11/dgemm-cblas.cc.  Obviously, it does not support cases besides MKL and MacOS.
