### ISSUE TITLE
SYCL needs improvements

### ISSUE THREAD

**Issue by jeffhammond** [ParRes/Kernels#313]
# Problems

- The performance of SYCL is not great right now, even with CodePlay ComputeCpp.  With triSYCL, it is very bad.  Are the implementations doing something incorrectly?

- Only transpose compiles with ProGTX.  The compiler complains about both nstream and transpose.  Are these bugs in the PRK or the implementation?

# Features 

- Use https://github.com/codeplaysoftware/sycl-blas for dgemm-sycl.

**Comment by jeffhammond** [comment]
SYCL is working well now.  Part of the issue with triSYCL performance in the early days was a build system mis-configuration where no compiler optimization was enabled.  Modern C++ does not perform well using `CXXFLAGS=-O0`...

**Comment by keryell** [comment]
Nice to see SYCL making some progress... ;-)
