### ISSUE TITLE
make clean requires cargo

### ISSUE THREAD

**Issue by jdinan** [ParRes/Kernels#361]
## Summary of the issue

Running `make clean` now has a dependency on RUST cargo.  We encountered this issue during SOS CI testing under Travis where cargo is not installed (https://github.com/Sandia-OpenSHMEM/SOS/blob/master/.travis.yml#L381).  As a workaround we will try installing the cargo package.  As long as package installation doesn't substantially increase our build times this solution should be fine for us; however, I would imagine that many HPC systems won't have the RUST tools installed and more folks will run into this issue.

This may be related to issue #312.

## What type of issue is this?

- [x] Build system

## Where does this bug appear?

Check all that apply:
  - [ ] MacOS
  - [x] Linux
  - [ ] Cray
  - [x] GCC
  - [ ] Clang
  - [ ] Intel compiler
  - [ ] MPICH and derivatives (MVAPICH2, Intel MPI, Cray MPI, etc.)
  - [ ] Open-MPI

### Operating system

Travis Ubuntu image

## Output showing problem

```
make[1]: Leaving directory `/home/travis/travis/src/PRK/C1z'
make -C RUST clean
make[1]: Entering directory `/home/travis/travis/src/PRK/RUST'
cd p2p && cargo clean
/bin/sh: 1: cargo: not found
make[1]: *** [clean] Error 127
make[1]: Leaving directory `/home/travis/travis/src/PRK/RUST'
make: *** [clean] Error 2
```

**Comment by jeffhammond** [comment]
I'm sorry this happened.  Rust is so unimportant in the grand scheme of things that I will just remove it from the master makefile.
