### ISSUE TITLE
print kernel name and version before parsing input

### ISSUE THREAD

**Issue by jeffhammond** [ParRes/Kernels#4]
We should print the name and version of the kernel even before processing the input parameters. That way, when we report an error in those parameters that lands in a script’s output, we know to which kernel it belongs. - @rfvander

**Comment by rfvander** [comment]
Done

**Comment by jeffhammond** [comment]
Committed to Intel repo?  Once we get everything on Github, there's a cool trick where you can add something like "resolves #42" and it will close issue 42 automatically when you push.

**Comment by rfvander** [comment]
Indeed, committed to Intel repo. Eagerly awaiting more time savers!

Rob
