### ISSUE TITLE
Broken link in Readme to docs

### ISSUE THREAD

**Issue by hattom** [ParRes/Kernels#500]
## What type of issue is this?

- [ ] Bug in the code or other problem
- [X] Inadequate/incorrect documation
- [ ] Feature request

The at the bottom of **Build instructions**, under the compiler table, there's a broken link:
`Please see the documentation in the [https://github.com/ParRes/Kernels/tree/default/doc](documentation (doc) subdirectory).`
and the link is pointing at:
`https://github.com/ParRes/Kernels/tree/default/doc](documentation`

**Comment by jeffhammond** [comment]
Thanks!
