### ISSUE TITLE
add HPX kernels

### ISSUE THREAD

**Issue by jeffhammond** [ParRes/Kernels#51]
These are being implemented.  Add to the repo when appropriate.

HPX = HPX-5 from IU

**Comment by rfvander** [comment]
We are also expecting HPX-3 kernels from LSU any moment. Can you start to prepare for that?

**Comment by jeffhammond** [comment]
Yes.  HPX-3 is addressed in https://github.com/ParRes/Kernels/issues/32.  I will work on the Travis support for that now.

**Comment by rfvander** [comment]
Splendid! I missed that one.

**Comment by jeffhammond** [comment]
I can't get the necessary Boost packages from apt so I need to work out building Boost from source for HPX-3, which is unpleasant.  I should be able to get them from Homebrew with more ease though, so I might just test only on Mac OS to start.

https://travis-ci.org/jeffhammond/PRK/jobs/103502973

**Comment by jeffhammond** [comment]
Once again, Boost+CMake collaborate to steal happiness from my life: https://github.com/STEllAR-GROUP/hpx/issues/1964

**Comment by jeffhammond** [comment]
HPX++ is the only thing I care about at this point.
