### ISSUE TITLE
Charm++/AMPI SMP-build runtime parameters missing

### ISSUE THREAD

**Issue by SamTWhite** [ParRes/Kernels#53]
SMP builds of Charm++ and AMPI currently require that users provide runtime parameters for the numbers of worker threads and communication threads desired per node, for best performance on a variety of node architectures.

SMP mode means that the runtime has a dedicated communication thread for each process. So in addition to '+p N' which represents the total number of processing elements available for application chares to run on, you will want to add '++ppn' to specify the number of processing elements (cores/hyperthreads) per node.

Additionally you can set the mapping of worker and communication threads within a process using '+pemap' to specify the mapping of worker PEs within a node and '+commap' to specify the mapping of communication threads within a node.

A simple SMP build run command on a node with 8 cores, using 1 process with 7 worker threads and 1 dedicated communication thread would be:
./charmrun  ./program +p 7 ++ppn 7

Or with explicit PE and comm. thread mapping:
 ./charmrun  ./program +p 7 ++ppn 7 +pemap 0-6 +commap 7

I see in the travis build script that you are building Charm++/AMPI in SMP mode, but that the test scripts do not use these options. Running in SMP mode without passing these parameters should generate some warnings at the top of charmrun's output about oversubscribing threads to your available resources if you run with a large enough '+p' option compared your machine's core count. The current default will assume that the '+p N' option is how many processes you want if there is no '++ppn' option, and then assign one worker thread and one comm. thread for each of those processes, generating 2*N threads in total.

We are working on an automated/portable command line option that will pick a reasonable configuration for a given machine. Here is some more information on the current runtime parameters:
http://charm.cs.illinois.edu/manuals/html/charm++/C.html#SECTION05322000000000000000

**Comment by rfvander** [comment]
Please note that the travis script is used for correctness testing, not for performance. We do not expect anyone--nor will we ourselves--run in the mode used for the tests.

**Comment by jeffhammond** [comment]
If I build for SMP mode, I should not have to tell Charm++/AMPI again that I am running in SMP mode when I run with said build, any more than I should have tell Charm++/AMPI that I'm running on InfiniBand if I have built it with the InfiniBand conduit.

**Comment by SamTWhite** [comment]
@rfvander Thanks, I wanted to make sure. I'll close the issue then.

@jeffhammond Yes, I think the problem is that historically Charm++ has thought of PEs as anything that a chare can live/run on and '+p' signifies that rather than the total number of cores the runtime should use. There will be a better interface for this soon that is more in line with what other common job launchers use.
